### ISSUE TITLE
API Call Failed: Unauthorized

### ISSUE THREAD

**Issue by szmark02** [warmans/rsk-search#25]
Authorization failed with reason: token is either expired or not yet active.

Error comes up on every page load. Also the timestamps are not working on phone browser anymore - don't know if this is connected.

**Comment by warmans** [comment]
Hi, thanks for letting me know. Are you seeing the error while logged-in or as a guest? If you are logged-in, have you tried logging out and back in again? It could be that the token is actually expired and I'm not handling it properly.

The timestamp think is a bit weird, it could also be caused by a older cached version of the UI application but I'm not sure how to do a hard refresh on most phone browsers. If your browser has an incognito mode it could be worth checking with that if it solved the problem. If so it probably just means it will eventually refresh the cache and fix itself.

**Comment by szmark02** [comment]
Yes, I was logged in, and logging out and back in again did solve the issue indeed, thanks!

I tried the incognito mode on the phone, but still the same: if I tap a timestamp it will start playback from the beginning only.

**Comment by warmans** [comment]
This should fix the token issue: https://github.com/warmans/rsk-search/commit/4ef7418ccc84d9c6bebdd537f0633e0db55fd534

For the offsets, may I ask which episode you are seeing this issue on? Or is it all of them?
