### ISSUE TITLE
Multiple trivia lines close to each other

### ISSUE THREAD

**Issue by szmark02** [warmans/rsk-search#37]
When having 2 separate lines of trivia next or within a couple of lines of each other, the second one is not appearing (see image, only the first one appears on the preview page).
![image](https://github.com/warmans/rsk-search/assets/108570026/c564a149-a878-4204-bfd4-96fa185cbd48)

**Comment by warmans** [comment]
That's odd, I wonder if it's a bug in the transcript parser or in the UI. I'll do some testing later and see if I can figure it out. 

Thanks for reporting.

**Comment by warmans** [comment]
This was a bug in the transcript display. The code didn't work if there were multiple trivias for the same line of dialog. In the given example this is less obvious because the first trivia doesn't wrap any line. But when it parses it it will assume this relates to the next line. 

Should be fixed now :pray:

**Comment by szmark02** [comment]
Great, thanks for checking it!On 2023. Jul 15., at 13:32, SW ***@***.***> wrote:﻿
Closed #37 as completed.
